### ISSUE TITLE
URGENT! Fix program so it outputs ONLY "Hello World!"

### ISSUE THREAD

**Issue by MoonWolf125** [MSUM-ACM/ACMGitWorkshop#1]

**Comment by MoonWolf125** [comment]
Would appreciate some help if @KyleFiala was able to help with this! We need this done by Thursday night at the latest!

**Comment by KyleFiala** [comment]
Urgent issue handled, good work team (*Self High-Five*)!

**Comment by MoonWolf125** [comment]
Fixed in commit 029abd8157b66d97fb4ce71348cca77111c07a33 by @KyleFiala
